### ISSUE TITLE
Reply-to support?

### ISSUE THREAD

**Issue by alwest** [elkurczako/Double-Opt-in-for-CF7#1]
Hi, this is a useful plugin which screens out most of the bogus contact form submissions that use a fake or spoofed email addresses.

I have a couple of comments -

Once the email has been validated, the plugin sends 2 emails - a) to the site admin or other contact (the responder) and b) to the person who filled in the form in the first place (the enquirer) -

1. **Email a)** should have an option to specify a "Reply-to" address (i.e. the enquirer) - just like CF7 does - because the responder usually wants to reply directly to the enquirer.  NB most web hosts won't allow "From;" to be set to an external domain, so REply-to is used instead.

2. **Email b)** is probably superfluous because the enquirer has already had one email from me (requesting email verification) and has also visited my site to verify their identity.  An obvious way to do this is to leave the Subject field of the second email blank in the config screen - but this causes an error when the enquirer tries to validate.

I've fixed 2. by easily modifying the plugin's PHP -- but 1. seems a little more difficult to achieve!

**Comment by elkurczako** [comment]
Hi,
Thank you for your kind words about my plugin. I have some plans to add a few features in the future. 
The biggest (and probably most distant) is a modified CF7 form editor, allowing easier building WCAG compliant forms. But it has to wait until I'll have the time.
About your comments. I'll do some fixes and tweaks (yours included) in a week or two. New release will also be tested for current WP version.
Thanks again.
